server:
  port: 8080
spring:
  servlet:
    multipart:
      #开启multipart上传功能
      enabled: true
      #文件写入磁盘的阈值
      file-size-threshold: 2KB
      #最大文件大小
      max-file-size: 200MB
      #最大请求大小
      max-request-size: 215MB
#文件存储所需参数
#所有通过 REST API 上传的文件都将存储在此目录下  file.upload.path =D:/aplus为自定义参数
file:
  upload:
    path: D:/aplus
